[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
pact_consumer = "1.3.1"
aws-config = "1.5.17"
aws-sdk-backup = "1.64.0"
